version: '3'

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - adminerAuthenticationNetwork
      - adminerStoreNetwork

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - authenticationNetwork
      - adminerAuthenticationNetwork
    volumes:
      - authenticationVolume:/var/lib/mysql

  authenticationDBMigration:
    image: authdbmigration
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - authenticationNetwork

  authenticationContainer:
    image: myauthenticationimage
    environment:
      - DATABASE_URL=authenticationDatabase
    ports:
      - 5002:5002
    networks:
      - authenticationNetwork

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - customerNetwork
      - daemonNetwork
      - adminNetwork
      - adminerStoreNetwork
    volumes:
      - storeVolume:/var/lib/mysql

  databaseMigration:
    image: storedbmig
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    networks:
      - customerNetwork
      - daemonNetwork
      - adminNetwork

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redisDaemonNetwork
      - redisWarehouseNetwork

  customer:
    image: customer
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    ports:
      - 5003:5003
    networks:
      - customerNetwork
    deploy:
      replicas: 3

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    networks:
      - daemonNetwork
      - redisDaemonNetwork

  warehouse:
    image: warehouse
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    ports:
      - 5001:5001
    networks:
      - warehouseNetwork
      - redisWarehouseNetwork
    deploy:
      replicas: 3

  admin:
    image: admin
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    ports:
      - 5004:5004
    networks:
      - adminNetwork

networks:
  customerNetwork:
    driver: overlay

  warehouseNetwork:
    driver: overlay

  adminNetwork:
    driver: overlay

  daemonNetwork:
    driver: overlay

  authenticationNetwork:
    driver: overlay

  redisDaemonNetwork:
    driver: overlay

  redisWarehouseNetwork:
    driver: overlay

  adminerAuthenticationNetwork:
    driver: overlay

  adminerStoreNetwork:
    driver: overlay

volumes:

  authenticationVolume:

  storeVolume: