version: '3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
  adminer:
    image: adminer
    ports:
      - 8081:8080
  databaseMigration:
    image: storedbmig
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    depends_on:
      database:
        condition: service_healthy
  redis:
    image: redis
    ports:
      - 6379:6379
  customer:
    image: customer
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    depends_on:
      - databaseMigration
    ports:
      - 5003:5003
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    depends_on:
      - databaseMigration
  warehouse:
    image: warehouse
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    depends_on:
      - databaseMigration
    ports:
      - 5001:5001
  admin:
    image: admin
    environment:
      - DATABASE_URL=database
      - REDIS_PORT=redis
    depends_on:
      - databaseMigration
    ports:
      - 5004:5004